version: '3.9'

services:
  youtube-app:
    image: ansh-youtube-app
    build: .
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=youtube-data
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis
      - REDIS_DB=0
    ports:
      - 80:80
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn youtube_api_project.wsgi:application --bind 0.0.0.0:80"
  
  postgres:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=youtube-data
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - "postgresData:/var/lib/postgres/data"
  
  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    volumes:
      - "redisData:/data"
  
volumes:
  postgresData:
  redisData:

    
  
